homeassistant:
  auth_providers:
   - type: homeassistant
  # customize: !include customize.yaml
  # packages: !include_dir_named packages

# Enables configuration UI
frontend: 
  javascript_version: latest
  themes: !include_dir_merge_named themes

config:

hassio:

http:

updater:

conversation:

# history: !include history.yaml

# recorder: !include recorder.yaml

lovelace:
  mode: yaml

system_health:

logbook:

sun:

ssdp:

zeroconf:

person:

mobile_app:

logger:
  default: critical

august:
  login_method: phone
  username: !secret august_phone
  password: !secret august_password

eight_sleep:
  username: !secret eight_email
  password: !secret eight_password

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily

lovelace_gen:

sensor: !include_dir_merge_list sensor
