icon: mdi:settings
title: Einstellungen
popup_cards:
  input_boolean.motion_sensor_flur_toggle:
    title: Timeout
    card:
      type: entities
      entities:
        - input_datetime.motion_sensor_flur
  input_boolean.motion_sensor_bad_toggle:
    title: Timeout
    card:
      type: entities
      entities:
        - input_datetime.motion_sensor_bad
  input_boolean.motion_sensor_kuche_toggle:
    title: Timeout
    card:
      type: entities
      entities:
        - input_datetime.motion_sensor_kuche
  input_boolean.motion_sensor_wohnzimmer_toggle:
    title: Timeout
    card:
      type: entities
      entities:
        - input_datetime.motion_sensor_wohnzimmer
  input_boolean.motion_sensor_schlafzimmer_toggle:
    title: Timeout
    card:
      type: entities
      entities:
        - input_datetime.motion_sensor_schlafzimmer
cards:
  - type: vertical-stack
    cards:
      - !include
        - ../includes/titles.yaml
        - title: EINSTELLUNGEN

      - type: entities
        style: !include ../includes/style_entities.yaml
        entities:
          - input_boolean.notifications
          - input_boolean.auto_open_door
          - input_boolean.notify_door_left_open
          - input_boolean.cinema_lights

      - !include
        - ../includes/titles.yaml
        - title: GASTMODUS
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            style: !include ../includes/style_entities.yaml
            entities:
              - input_boolean.guest_mode
          - type: conditional
            conditions:
              - entity: input_boolean.guest_mode
                state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: custom:button-card
                  entity: input_datetime.guest_mode
                  show_state: true
                  show_icon: false
                  show_name: false
                  tap_action:
                    action: more-info
                  styles:
                    card:
                      #- width: 250px
                      - height: 30px
                      - font-size: 14px
                      - box-shadow: unset
                      - background: none
                - type: custom:button-card
                  entity: input_number.guest_mode_num_guests
                  show_state: true
                  show_icon: true
                  show_name: false
                  layout: icon_state
                  tap_action:
                    action: more-info
                  styles:
                    card:
                      - background: none
                      - width: 150px
                      - height: 30px
                      - font-size: 14px
                      - box-shadow: unset

  - type: vertical-stack
    cards:
      - !include
        - ../includes/titles.yaml
        - title: BEWEGUNGSMELDER

      - type: entities
        style: !include ../includes/style_entities.yaml
        entities:
          - input_boolean.motion_sensor_flur_toggle
          - input_boolean.motion_sensor_bad_toggle
          - input_boolean.motion_sensor_kuche_toggle
          - input_boolean.motion_sensor_wohnzimmer_toggle
          - input_boolean.motion_sensor_schlafzimmer_toggle

      - !include
        - ../includes/titles.yaml
        - title: STROMKOSTEN

      - type: entities
        style: !include ../includes/style_entities.yaml
        entities:
          - input_number.kwh_cost
